### ISSUE TITLE
Cannot run in Manjaro Linux KDE latest release

### ISSUE THREAD

**Issue by benchile55** [keshavbhatt/red#1]
Hello there,

I wanted to give a try to your newest release of Red-app  in my Manjaro Linux Kde (updated to latest release).  I checked all dependencies requested in terminal,  also checked libxcb plugins( installed) and gtk modules dependencies are all installed ( libcanberra modules in multilib packages are installed and appmenu-gtk-module is also installed) 
Then running presented a segmentation fault error which  I guess it can be  as the result of code  or denied memory access.. and finally I also tried installing as root user but it was the same situation. Refreshed snap packages and uninstalled and reinstalled them but showed the same bash result. 
![image](https://user-images.githubusercontent.com/61207930/77861803-b0770780-71ed-11ea-9074-093eae80c0e0.png)

Can you suggest any other ideas please ? 
Keep safe.

**Comment by keshavbhatt** [comment]
there is nothing wrong in code, 
try 
`export QT_DEBUG_PLUGINS=1`
`red-app` 
to see if all executable able to find all qt plugins required to run. provide the output.

**Comment by keshavbhatt** [comment]
also provide output of `snap list`

**Comment by benchile55** [comment]
El Sun, 29 Mar 2020 18:03:07 -0700
Keshav Bhatt <notifications@github.com> escribió:
> there is nothing wrong in code, 
> try 
> `export QT_DEBUG_PLUGINS=1`
> `red-app` 
> to see if all executable able to find all qt plugins required to run.
> provide the output.
> 

Hello,
Sending you attached  running test for Qtplugins and also a pic  with
the snap list result.

https://i.imgur.com/PCJOBUg.png

**Comment by keshavbhatt** [comment]
can you try reinstalling the with `snap remove red-app --purge` and `snap install red-app` ?

**Comment by benchile55** [comment]
El Sun, 29 Mar 2020 23:09:09 -0700
Keshav Bhatt <notifications@github.com> escribió:
> can you try reinstalling the with `snap remove red-app --purge` and
> `snap install red-app` ?
> 
> 

I just did your suggestion and it is still the same situation, showing
the same output from the bash ( link).

https://i.imgur.com/JJd0L2V.png

**Comment by keshavbhatt** [comment]
i found similar issue here check https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4551

**Comment by keshavbhatt** [comment]
snap specific issue happening on arch distro is discussed here : 
https://forum.snapcraft.io/t/python3-qt-application-on-arch-linux-segmentation-fault-core-dumped/15333

**Comment by benchile55** [comment]
El Mon, 30 Mar 2020 09:06:36 -0700
Keshav Bhatt <notifications@github.com> escribió:
> snap specific issue happening on arch distro is discussed here : 
> https://forum.snapcraft.io/t/python3-qt-application-on-arch-linux-segmentation-fault-core-dumped/15333
> 

Yes this topic makes quite sense.. for I have also tried installing
different snap apps  and many of them have not been installed correctly
showing this same segmentation fault core dumped error. Hmmm I will
contact some experienced friends from Manjaro Forum maybe they can have
some ideas or suggestions for testing procedures to install snaps
different from the regular cli or snap commands.

Thanks for your tip, really appreciate it!

**Comment by keshavbhatt** [comment]
i have cross referenced this in the snapcraft forum to that ppl there can know about the issue. 
thanks for reporting.

**Comment by dragonhelios** [comment]
as a work around. I squashed the snap and copied the red executabe fro the bin folder. seems to run fine in my manjaro install. Issue seems to be snap and arch based related from what I've been able to read.

**Comment by keshavbhatt** [comment]
good.

**Comment by keshavbhatt** [comment]
The issue is caused if user opens app from app launcher while the content snap is still being downloded by snapd. ([Reported here in snapcrat forums](https://forum.snapcraft.io/t/installation-of-snap-with-content-snap-as-dependency/16103/12))

If anyone facing the same issue with snap installs:
Here is the solution https://github.com/keshavbhatt/BingWall/issues/16


`sudo rm /var/cache/fontconfig/*`
`rm ~/.cache/fontconfig/*`
`fc-cache -r`
