### ISSUE TITLE
sudo snap install red-app freezes

### ISSUE THREAD

**Issue by casperl** [keshavbhatt/red#3]
Hi, 
I issued the command sudo snap install red-app on Ubuntu 19.04 and the installation freezes at the line "Automaticallly connect eligible plugs and slots..." 

Assuming this is a question, I entered y,Y,yes,Yes,n,No with no effect.

![image](https://user-images.githubusercontent.com/1303185/85538242-fd178680-b614-11ea-98bb-63e220fb4a8a.png)

**Comment by keshavbhatt** [comment]
As the output mentions, that "Automatically connect eligible plugs and slots" actually snapd is downloading required runtime snap which is required by red-app i.e, [Qt513-runtime-snap](https://snapcraft.io/qt513) for running. 
Wait for it to be completed.
Also please report this as an issue to forum.snapcraft.io , mention that "Show progress of downloading content snap as part of consumer snap installation" .
